agent:
    type: "rosbag"
    id: 0

ROS:
    SENSORS:
        color:
            is_valid: true
            rostopic_name: "/osr/image_color"
            camerainfo_rostopic_name: "/osr/image_color_camerainfo"
        depth:
            is_valid: true
            rostopic_name: "/osr/image_aligned_depth"
            camerainfo_rostopic_name: "/osr/image_depth_camerainfo"
            clip:
                value: -1
                min_distance: 1000
                max_distance: 15000
        thermal:
            is_valid: true
            rostopic_name: "/osr/image_thermal"
            camerainfo_rostopic_name: "/osr/image_thermal_camerainfo"
        infrared:
            is_valid: true
            rostopic_name: "/osr/image_ir"
            camerainfo_rostopic_name: "/osr/image_ir_camerainfo"
        nightvision:
            is_valid: true
            rostopic_name: "/osr/image_nv1"
            camerainfo_rostopic_name: "NULL"
        lidar:
            is_valid: false
            rostopic_name: "/osr/lidar_pointcloud"
            camerainfo_rostopic_name: "NULL"

MODULE:
    SEG:
        name: "DeepLabv3"