env:
    type: "dynamic"
    id: "03"
#    time: "day"

screen_compensate: false

machine_name: "snu"

sensors:
    color:
        is_valid: true
        rostopic_name: "/osr/image_color"
        camerainfo_rostopic_name: "/osr/image_color_camerainfo"
    disparity:
        is_valid: false
        rostopic_name: "/osr/image_aligned_depth"
        camerainfo_rostopic_name: "/osr/image_depth_camerainfo"
        clip:
            value: -1
            min_distance: 1000
            max_distance: 15000
    thermal:
        is_valid: true
        rostopic_name: "/osr/image_thermal"
        camerainfo_rostopic_name: "/osr/image_thermal_camerainfo"
    infrared:
        is_valid: false
        rostopic_name: "/osr/image_ir"
        camerainfo_rostopic_name: "/osr/image_ir_camerainfo"
    nightvision:
        is_valid: false
        rostopic_name: "/osr/image_nv1"
        camerainfo_rostopic_name: "NULL"
    lidar:
        is_valid: true
        rostopic_name: "/osr/lidar_pointcloud"
        camerainfo_rostopic_name: "NULL"

segmentation:
    name: "DeepLabv3"
    device: 0
    run: false
    visualization:
        is_draw: false
        is_show: false
        auto_save: false
        is_result_publish: false
        result_rostopic_name: "/osr/snu_seg_result_image"

attnet:
    name: "ATT"
    device: 0
    run: false

detector:
    name: "YOLOv5"
    device: 0
    run:
        augment: False
        conf_thres: 0.25
        iou_thres: 0.45
        weight_path: '/home/snu/SNU_USR_dev/src/snu_module/models/detector/YOLOv5/day/'
        model_name: 'yolov5m_coco_thermal_pretrained.pth'
    sensors:
        color: true
        disparity: false
        thermal: true
        infrared: false
        nightvision: false
        lidar: false
    visualization:
        is_draw: true
        is_show: false
        auto_save: false
        bbox_color: (255, 0, 0)
        is_result_publish: true

tracker:
    name: "Custom"
    device: 0
    association:
        trk:
            init_age: 2
            destroy_age: 3
            similarity_thresh: 0.325
        trk_cand:
            destroy_age: 2
            similarity_thresh: 0.6
    visualization:
        is_draw: true
        is_show: false
        auto_save: false
        is_result_publish: true

aclassifier:
    name: "Custom"
    device: 0
    sensors:
        thermal: true
    visualization:
        is_draw: true
        is_show: false
