agent:
    type: "rosbagfile"
    daytime: "day"

sensors:
    color:
        is_valid: true
        rostopic_name: "/osr/image_color"
        camerainfo_rostopic_name: "/camera/color/camera_info"
    disparity:
        is_valid: true
        rostopic_name: "/osr/image_depth"
        camerainfo_rostopic_name: "/camera/depth/camera_info"
        clip:
            value: -1
            min_distance: 1000
            max_distance: 15000
    thermal:
        is_valid: true
        rostopic_name: "/osr/image_thermal"
        camerainfo_rostopic_name: "NULL"
    infrared:
        is_valid: true
        rostopic_name: "/osr/image_infrared"
        camerainfo_rostopic_name: "NULL"
    nightvision:
        is_valid: true
        rostopic_name: "/osr/image_nv1"
        camerainfo_rostopic_name: "NULL"
    lidar:
        is_valid: true
        rostopic_name: "/osr/camera_lidar"
        camerainfo_rostopic_name: "NULL"

visualization:
    detection:
        show: false
    tracking:
        show: true
    aclassification:
        show: false