agent:
    type: "rosbagfile"
    name: "190823_kiro_lidar_camera_calib"
    daytime: "day"
    screen_compensate: true

sensors:
    color:
        is_valid: true
        rostopic_name: "/osr/image_color"
        camerainfo_rostopic_name: "/camera/color/camera_info"
    disparity:
        is_valid: true
        rostopic_name: "/osr/image_aligned_depth"
        camerainfo_rostopic_name: "/camera/depth/camera_info"
        clip:
            value: -1
            min_distance: 1000
            max_distance: 15000
    thermal:
        is_valid: true
        rostopic_name: "/osr/image_thermal"
        camerainfo_rostopic_name: "NULL"
    infrared:
        is_valid: true
        rostopic_name: "/osr/image_ir"
        camerainfo_rostopic_name: "NULL"
    nightvision:
        is_valid: true
        rostopic_name: "/osr/image_nv1"
        camerainfo_rostopic_name: "NULL"
    lidar:
        is_valid: true
        rostopic_name: "/osr/lidar_pointcloud"
        camerainfo_rostopic_name: "NULL"

detector:
    name: "YOLOv4"
    device: 0
    visualization:
        is_draw: true
        is_show: true
        auto_save: false
        bbox_color: (255, 0, 0)
    is_result_publish: true
    result_rostopic_name: "/osr/snu_det_result_image"

tracker:
    name: "Custom"
    device: 0
    visualization:
        is_draw: true
        is_show: true
        auto_save: false
        top_view:
            is_draw: false
            is_show: false
            # map_size -> (depth_range, horizontal length*2)
            map_size: (15000, 5000)
            trk_radius: 100
    is_result_publish: true
    result_rostopic_name: "/osr/snu_trk_acl_result_image"

aclassifier:
    name: "Custom"
    device: 0
    visualization:
        is_draw: true
        is_show: false
